/*
 * GroupDocs.Conversion Cloud API Reference
 *
 * Please visit [Dashboard](https://dashboard-qa.groupdocs.cloud/#/applications) to obtain your Client Id and Client Secret keys.
 *
 * API version: 24.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Represents field label
type FieldLabel struct {
	Field *FieldLabelField `json:"Field"`
	// The label e.g. \"Sender\"
	Label string `json:"Label,omitempty"`
}
