/*
 * GroupDocs.Conversion Cloud API Reference
 *
 * Please visit [Dashboard](https://dashboard-qa.groupdocs.cloud/#/applications) to obtain your Client Id and Client Secret keys.
 *
 * API version: 24.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Error
type ModelError struct {
	// Code
	Code string `json:"Code,omitempty"`
	// Message
	Message string `json:"Message,omitempty"`
	// Description
	Description string `json:"Description,omitempty"`
	// Inner Error
	InnerError *ErrorDetails `json:"InnerError,omitempty"`
}
